ToDoList/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('tasks.urls')),
    path('members/', include('members.urls')),
    path('accounts/', include('django.contrib.auth.urls')),  # Include the aut
]

tasks/urls.py
from django.urls import path
from . import views
from django.urls import include


urlpatterns = [
    # Path Converters
    # int: numbers
    # str: strings
    # path: whole urls /
    # slug: hyphen-and_underscores_stuff
    # UUID: universally unique identifier

    # Home Page
    path('', views.all_tasks),

    # All Tasks pages
    path('tasks', views.all_tasks, name="all-tasks"),  # all tasks
    path('todo_task/<task_id>', views.todo_all_task, name='todo-all-task'),  # todo all task
    path('task/<int:task_id>', views.task_detail_all, name='all-task-detail'),  # task detail
    path('delete_task/<task_id>', views.delete_all_task, name='delete-all-task'),  # delete task

    # Overdue Tasks pages
    path('overdue_tasks', views.overdue_tasks, name='overdue-tasks'),  # overdue tasks
    path('todo_overdue_task/<task_id>', views.todo_overdue_task, name='todo-overdue-task'),  # todo overdue task
    path('overdue_task/<int:task_id>', views.task_detail_overdue, name='overdue-task-detail'),  # overdue task detail
    path('delete_overdue_task/<task_id>', views.delete_overdue_task, name='delete-overdue-task'),  # delete overdue task

    # Today Tasks pages
    path('today_tasks', views.today_tasks, name='today-tasks'),  # today tasks
    path('todo_today_task/<task_id>', views.todo_today_task, name='todo-today-task'),  # todo today task
    path('today_task/<int:task_id>', views.task_detail_today, name='today-task-detail'),  # today task detail
    path('delete_today_task/<task_id>', views.delete_today_task, name='delete-today-task'),  # delete today task

    # Completed Tasks pages
    path('Completed', views.completed_tasks, name='completed-tasks'),  # completed tasks
    path('cancel_todo_task/<task_id>', views.cancel_todo_task, name='cancel-todo-task'),  # cancel todo task
    path('completed_task/<int:task_id>', views.task_detail_completed, name='completed-task-detail'),  # completed task detail
    path('delete_completed_task/<task_id>', views.delete_completed_task, name='delete-completed-task'),  # delete completed task

    # Tags pages
    path('all_tags', views.all_tags, name="all-tags"),  # all tags
    path('tag/<tag_id>', views.tag, name="tag-detail"),  # tag detail
    path('delete_tag/<tag_id>', views.delete_tag, name="delete-tag"),  # delete tag
    path('todo_filtered_task/<task_id>', views.todo_filtered_task, name='todo-filtered-task'),  # todo filtered task
    path('delete_tagged_task/<task_id>', views.delete_filtered_task, name='delete-filtered-task'),  # delete filtered task
    path('fiter_by_tag/<tag_id>', views.tag_filter, name='fiter-by-tag'),  # filter by tag
    path('tag_filter_task/<str:tag_id>/<int:task_id>/', views.tag_filter_task, name='tag-filter-task'),  # tag filter task
]

tasks/models.py
# tasks/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User


class Task(models.Model):
    """
    Represents a task in the task management system.

    Attributes:
        id (int): The primary key for the task.
        user (User): The user to whom the task is assigned.
        title (str): The title of the task.
        description (str): A detailed description of the task.
        tag (TagTask): The tag associated with the task.
        date (datetime): The date and time when the task was created.
        completed (bool): Indicates whether the task is completed.
    """

    id = models.AutoField(primary_key=True)
    user = models.ForeignKey('auth.User', on_delete=models.CASCADE, blank=True, null=True)
    title = models.CharField(max_length=200)
    description = models.TextField(blank=True)
    tag = models.ForeignKey('TagTask', on_delete=models.CASCADE, blank=True, null=True)
    date = models.DateTimeField(default=timezone.now, blank=True, null=True)
    completed = models.BooleanField(default=False)

    def __str__(self):
        return self.title


class TagTask(models.Model):
    """
    Represents a tag associated with tasks in the task management system.

    Attributes:
        id (int): The primary key for the tag.
        user_id (User): The user to whom the tag is assigned.
        tag_name (str): The name of the tag.
    """

    id = models.AutoField(primary_key=True)
    user_id = models.ForeignKey('auth.User', on_delete=models.CASCADE, blank=True, null=True)
    tag_name = models.CharField(max_length=200)

    def __str__(self):
        return self.tag_name

tasks/views.py
import datetime

from django.shortcuts import render, redirect
from django.http import Http404
from django.contrib.auth.decorators import login_required
from .forms import TaskForm, TagForm, TaskTagForm
from .models import Task, TagTask
from django.http import HttpResponse
from django.db.models import Q


@login_required
def output(request, html_page: str, context: dict) -> HttpResponse:
    """
     Renders the specified HTML page with the given context.

     :param request: HttpRequest object containing metadata about the request.
     :param html_page: str, the name of the HTML page to render.
     :param context: dict, the context data to pass to the template.

     :return: HttpResponse object with the rendered HTML page.
     """

    context["first_tags"] = TagTask.objects.filter(user_id=request.user)[:2]
    context["all_tags_count"] = Task.objects.filter(user_id=request.user, completed=False).count()
    context["completed_tags_count"] = Task.objects.filter(user_id=request.user, completed=True).count()
    context["today_tasks_count"] = Task.objects.filter(user=request.user, completed=False, date=datetime.date.today()).count()
    context["overdue_tasks_count"] = Task.objects.filter(user=request.user, completed=False, date__lt=datetime.date.today()).count()

    return render(request, html_page, context)


def overdue_tasks(request) -> HttpResponse:
    """
    Handles the display and submission of overdue tasks.

    This view function processes GET and POST requests for overdue tasks. For GET requests, it renders the overdue tasks
    page with a list of overdue tasks and a form to add new tasks. For POST requests, it processes the submitted form
    data to add a new task.

    :param request: The HTTP request object containing metadata about the request.
    :returns:
        - HttpResponse: A redirect to the 'all-tasks' page if a new task is successfully added.
        - HttpResponse: Renders the overdue tasks page with the list of overdue tasks and the task form for GET requests.
    """

    submitted = False
    if request.method == "POST":
        task_form = TaskForm(request.POST, user=request.user)
        if task_form.is_valid():
            event = task_form.save(commit=False)
            event.user = request.user
            event.save()
            return redirect('all-tasks')
    else:
        task_form = TaskForm(user=request.user, initial={'date': datetime.date.today()})

        if 'submitted' in request.GET:
            submitted = True

    tasks = Task.objects.filter(user=request.user, completed=False, date__lt=datetime.date.today())
    tasks_amount = tasks.count()

    return output(request, 'tasks/overdue_tasks.html', {
        "Text_of_the_page": "Overdue tasks",
        "amount": tasks_amount,
        "content_to_unpack": tasks,
        "form": task_form,
        'submitted': submitted,
        "edit": False,
    })


def todo_overdue_task(request, task_id: int) -> HttpResponse:
    """
    Toggles the completion status of an overdue task.

    This view function retrieves the task with the given task_id, toggles its completion status, saves the changes,
    and redirects the user to the overdue tasks page.

    :param request: The HTTP request object containing metadata about the request.
    :param task_id: The ID of the task to be toggled.
    :return: HttpResponse: A redirect to the overdue tasks page.
    """

    task_info = Task.objects.get(pk=task_id)
    task_info.completed = not task_info.completed
    task_info.save()
    return redirect('overdue-tasks')


def task_detail_overdue(request, task_id: int) -> HttpResponse:
    """
    Renders the task detail page for an overdue task.

    This view function retrieves the task with the given task_id, checks if the task belongs to the current user,
    and renders the task detail page. If the task does not belong to the current user, it raises a 404 error.
    If the form is valid, it saves the task and redirects to the overdue tasks page.

    :param request: The HTTP request object containing metadata about the request.
    :param task_id: The ID of the task to be detailed.
    :return: HttpResponse: A redirect to the overdue tasks page if the form is valid,
    otherwise renders the task detail page.
    """

    task_info = Task.objects.get(pk=task_id)

    if task_info.user != request.user:
        raise Http404("Task does not exist or you do not have permission to view it.")

    task_form = TaskForm(request.POST or None, instance=task_info, user=request.user)

    if task_form.is_valid():
        task_form.save()
        return redirect('overdue-tasks')

    tasks = Task.objects.filter(user=request.user, completed=False, date__lt=datetime.date.today())
    tasks_amount = tasks.count()

    return output(request, 'tasks/overdue_tasks.html', {
        "Text_of_the_page": "Overdue tasks",
        "amount": tasks_amount,
        "content_to_unpack": tasks,
        "form": task_form,
        "edit": True,
        "task": task_info,
    })


def delete_overdue_task(request, task_id: int) -> HttpResponse:
    """
    Deletes an overdue task.

    This view function retrieves the task with the given task_id, deletes it, and redirects the user to the overdue
    tasks page.

    :param request: The HTTP request object containing metadata about the request.
    :param task_id: The ID of the task to be deleted.
    :return: HttpResponse: A redirect to the overdue tasks page.
    """

    task_info = Task.objects.get(pk=task_id)
    task_info.delete()
    return redirect('overdue-tasks')


def today_tasks(request) -> HttpResponse:
    """
    Renders the today tasks page.

    This view function processes GET and POST requests for today's tasks. For GET requests, it renders the today tasks
    page with a list of today's tasks and a form to add new tasks. For POST requests, it processes the submitted form
    data to add a new task.

    :param request: The HTTP request object containing metadata about the request.
    :returns:
        - HttpResponse: A redirect to the 'today-tasks' page if a new task is successfully added.
        - HttpResponse: Renders the today tasks page with the list of today's tasks and the task form for GET requests.
    """

    submitted = False
    if request.method == "POST":
        task_form = TaskForm(request.POST, user=request.user, initial={'date': datetime.date.today()})
        if task_form.is_valid():
            event = task_form.save(commit=False)
            event.user = request.user
            event.save()
            return redirect('today-tasks')
    else:
        task_form = TaskForm(user=request.user, initial={'date': datetime.date.today()})

        if 'submitted' in request.GET:
            submitted = True

    tasks = Task.objects.filter(user=request.user, completed=False, date=datetime.date.today())
    tasks_amount = tasks.count()

    return output(request, 'tasks/today_tasks.html', {
        "Text_of_the_page": "Today tasks",
        "amount": tasks_amount,
        "content_to_unpack": tasks,
        "form": task_form,
        'submitted': submitted,
        "edit": False,
    })


def todo_today_task(request, task_id: int) -> HttpResponse:
    """
    Toggles the completion status of a task for today.

    This view function retrieves the task with the given task_id, toggles its completion status, saves the changes,
    and redirects the user to the today tasks page.

    :param request: The HTTP request object containing metadata about the request.
    :param task_id: The ID of the task to be toggled.
    :return: HttpResponse: A redirect to the today tasks page.
    """

    task_info = Task.objects.get(pk=task_id)
    task_info.completed = not task_info.completed
    task_info.save()
    return redirect('today-tasks')


def task_detail_today(request, task_id: int) -> HttpResponse:
    """
    Renders the task detail page for a task scheduled for today.

    This view function retrieves the task with the given task_id, checks if the task belongs to the current user,
    and renders the task detail page. If the task does not belong to the current user, it raises a 404 error.
    If the form is valid, it saves the task and redirects to the today tasks page.

    :param request: The HTTP request object containing metadata about the request.
    :param task_id: The ID of the task to be detailed.
    :return: HttpResponse: A redirect to the today tasks page if the form is valid, otherwise renders the task detail
    page.
    """

    task_info = Task.objects.get(pk=task_id)

    if task_info.user != request.user:
        raise Http404("Task does not exist or you do not have permission to view it.")

    task_form = TaskForm(request.POST or None, instance=task_info, user=request.user)

    if task_form.is_valid():
        task_form.save()
        return redirect('today-tasks')

    tasks = Task.objects.filter(user=request.user, completed=False, date=datetime.date.today())
    tasks_amount = tasks.count()

    return output(request, 'tasks/today_tasks.html', {
        "Text_of_the_page": "Today tasks",
        "amount": tasks_amount,
        "content_to_unpack": tasks,
        "form": task_form,
        "edit": True,
        "task": task_info,
    })


def delete_today_task(request, task_id: int) -> HttpResponse:
    """
    Deletes a task scheduled for today.

    This view function retrieves the task with the given task_id, deletes it, and redirects the user to the today tasks
    page.

    :param request: The HTTP request object containing metadata about the request.
    :param task_id: The ID of the task to be deleted.
    :return: HttpResponse: A redirect to the today tasks page.
    """

    task_info = Task.objects.get(pk=task_id)
    task_info.delete()
    return redirect('today-tasks')


def all_tasks(request) -> HttpResponse:
    """
    Renders the all tasks page.

templates/tasks/all_tasks.html
{% extends 'tasks/template.html' %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

{% block tasks_content%}

        <div class="task-list-content">

            <div class="add task">
                <form action="{% url 'all-tasks' %}" method="POST" id="add-task-form">
                    {% csrf_token %}
                    <button class="btn custom-btn-4 full-width-btn" type="submit">&#43; Add new task</button>
                </form>
            </div>

            {% for cont in content_to_unpack %}
                <a href="{% url 'all-task-detail' cont.id %}" class="card-link custom-card-link">
                    <div class="card custom-card">
                        <div class="card-body d-flex justify-content-between align-items-center custom-card-body">
                            <div class="form-check custom-form-check">
                                <form action="{% url 'todo-all-task' cont.id %}" method="POST" id="form-{{ cont.id }}">
                                    {% csrf_token %}
                                    <input class="form-check-input custom-form-check-input" type="checkbox" name="completed" value="True" id="flexCheckDefault{{ cont.id }}" {% if cont.completed %}checked{% endif %} onchange="document.getElementById('form-{{ cont.id }}').submit();">
                                    <label class="form-check-label custom-form-check-label" for="flexCheckDefault{{ cont.id }}">
                                        {{ cont.title }}
                                    </label>
                                </form>
                            </div>
                            <span class="btn custom-btn"> <b>&#8618;</b> </span>
                        </div>
                    </div>
                </a>
            {% endfor %}
        </div>

{% endblock %}

{% block task_detail %}

<form method="post">
                   <div class="form-container">
                       <h2>Task:</h2>
                      {% csrf_token %}
                      <div class="form-group">
                        <label for="id_title">Title</label>
                        <div class="input-container">
                          <input type="text" name="title" id="id_title" class="form-control custom-title" value="{{ form.title.value|default_if_none:'' }}">
                        </div>
                      </div>
                      <div class="form-group">
                        <label for="id_description">Description</label>
                        <div class="input-container">
                          <textarea name="description" id="id_description" class="form-control custom-description">{{ form.description.value|default_if_none:'' }}</textarea>
                        </div>
                      </div>
                        <div class="form-group">
                          <label for="id_due_date">Due Date</label>
                          <div class="input-container">
                            <input type="date" name="date" id="id_due_date" class="form-control custom-due-date" value="{{ form.date.value|date:'Y-m-d'|default_if_none:'' }}">
                          </div>
                        </div>
                        <div class="form-group">
                            <label for="id_tags">Tags</label>
                            <div class="input-container">
                                {{ form.tag }}
                            </div>
                        </div>

                           {% if edit %}
                                <div class="button-group">
                                    <button type="submit" class="btn custom-submit custom-save-1">Save Changes</button>
                                    <a href="{% url 'delete-all-task' task.id %}" class="btn custom-submit custom-delete-1">Delete</a>
                                </div>
                           {% else %}
                                <button type="submit" class="btn custom-submit">Add Task</button>
                           {% endif %}
                   </div>
               </form>

{% endblock %}

</body>
</html>

templates/tasks/completed_tasks.html
{% extends 'tasks/template.html' %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

{% block tasks_content%}

        <div class="task-list-content">
            {% for cont in content_to_unpack %}
                <a href="{% url 'completed-task-detail' cont.id %}" class="card-link custom-card-link">
                    <div class="card custom-card">
                        <div class="card-body d-flex justify-content-between align-items-center custom-card-body">
                            <div class="form-check custom-form-check">
                                <form action="{% url 'cancel-todo-task' cont.id %}" method="POST" id="form-{{ cont.id }}">
                                    {% csrf_token %}
                                    <input class="form-check-input custom-form-check-input" type="checkbox" name="completed" value="True" id="flexCheckDefault{{ cont.id }}" {% if cont.completed %}checked{% endif %} onchange="document.getElementById('form-{{ cont.id }}').submit();">
                                    <label class="form-check-label custom-form-check-label" for="flexCheckDefault{{ cont.id }}">
                                        {{ cont.title }}
                                    </label>
                                </form>
                            </div>
                            <span class="btn custom-btn"> <b>&#8618;</b> </span>
                        </div>
                    </div>
                </a>
            {% endfor %}
        </div>

{% endblock %}

{% block task_detail %}

<form method="post">
                   <div class="form-container">
                       <h2>Task:</h2>
                      {% csrf_token %}
                      <div class="form-group">
                        <label for="id_title">Title</label>
                        <div class="input-container">
                          <input type="text" name="title" id="id_title" class="form-control custom-title" value="{{ form.title.value|default_if_none:'' }}">
                        </div>
                      </div>
                      <div class="form-group">
                        <label for="id_description">Description</label>
                        <div class="input-container">
                          <textarea name="description" id="id_description" class="form-control custom-description">{{ form.description.value|default_if_none:'' }}</textarea>
                        </div>
                      </div>
                        <div class="form-group">
                          <label for="id_due_date">Due Date</label>
                          <div class="input-container">
                            <input type="date" name="date" id="id_due_date" class="form-control custom-due-date" value="{{ form.date.value|date:'Y-m-d'|default_if_none:'' }}">
                          </div>
                        </div>
                        <div class="form-group">
                            <label for="id_tags">Tags</label>
                            <div class="input-container">
                                {{ form.tag }}
                            </div>
                        </div>

                           {% if edit %}
                                <div class="button-group">
                                    <button type="submit" class="btn custom-submit custom-save-1">Save Changes</button>
                                    <a href="{% url 'delete-completed-task' task.id %}" class="btn custom-submit custom-delete-1">Delete</a>
                                </div>
                           {% else %}
                                <button type="submit" class="btn custom-submit">Add Task</button>
                           {% endif %}
                   </div>
               </form>

{% endblock %}

</body>
</html>

templates/tasks/filter_by_tag.html
{% extends 'tasks/template.html' %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% block tasks_content %}

        <div class="tasks-content">
            <div class="add task">
                <form action="{% url 'fiter-by-tag' tag.id %}" method="POST" id="add-task-form">
                    {% csrf_token %}
                    <button class="btn custom-btn-4 full-width-btn" type="submit">&#43; Add new task</button>
                </form>
            </div>

        <div class="task-list-content">
            {% for task in content_to_unpack %}
                <a href="{% url 'tag-filter-task' tag.id task.id %}" class="card-link custom-card-link">
                    <div class="card custom-card">
                        <div class="card-body d-flex justify-content-between align-items-center custom-card-body">
                            <div class="form-check custom-form-check">
                                <form action="{% url 'todo-filtered-task' task.id %}" method="POST" id="form-{{ task.id }}">
                                    {% csrf_token %}
                                    <input class="form-check-input custom-form-check-input" type="checkbox" name="completed" value="True" id="flexCheckDefault{{ task.id }}" {% if task.completed %}checked{% endif %} onchange="document.getElementById('form-{{ task.id }}').submit();">
                                    <label class="form-check-label custom-form-check-label" for="flexCheckDefault{{ task.id }}">
                                        {{ task.title }}
                                    </label>
                                </form>
                            </div>
                            <span class="btn custom-btn"> <b>&#8618;</b> </span>
                        </div>
                    </div>
                </a>
            {% endfor %}
        </div>
    </div>

{% endblock %}


{% block task_detail %}

               <form method="post">
                   <div class="form-container">
                       <h2>Task:</h2>
                      {% csrf_token %}
                      <div class="form-group">
                        <label for="id_title">Title</label>
                        <div class="input-container">
                          <input type="text" name="title" id="id_title" class="form-control custom-title" value="{{ form.title.value|default_if_none:'' }}">
                        </div>
                      </div>
                      <div class="form-group">
                        <label for="id_description">Description</label>
                        <div class="input-container">
                          <textarea name="description" id="id_description" class="form-control custom-description">{{ form.description.value|default_if_none:'' }}</textarea>
                        </div>
                      </div>
                        <div class="form-group">
                          <label for="id_due_date">Due Date</label>
                          <div class="input-container">
                            <input type="date" name="date" id="id_due_date" class="form-control custom-due-date" value="{{ form.date.value|date:'Y-m-d'|default_if_none:'' }}">
                          </div>
                        </div>
                        <div class="form-group">
                            <label for="id_tags">Tags</label>
                            <div class="input-container">
                                {{ form.tag }}
                            </div>
                        </div>

                           {% if edit %}
                                <div class="button-group">
                                    <button type="submit" class="btn custom-submit custom-save-1">Save Changes</button>
                                    <a href="{% url 'delete-filtered-task' task.id %}" class="btn custom-submit custom-delete-1">Delete</a>
                                </div>
                           {% else %}
                                <button type="submit" class="btn custom-submit">Add Task</button>
                           {% endif %}


                   </div>
               </form>

{% endblock %}
</body>
</html>

templates/tasks/overdue_tasks.html
{% extends 'tasks/template.html' %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

{% block tasks_content%}

        <div class="task-list-content">

            <div class="add task">
                <form action="{% url 'overdue-tasks' %}" method="POST" id="add-task-form">
                    {% csrf_token %}
                    <button class="btn custom-btn-4 full-width-btn" type="submit">&#43; Add new task</button>
                </form>
            </div>

            {% for cont in content_to_unpack %}
                <a href="{% url 'overdue-task-detail' cont.id %}" class="card-link custom-card-link">
                    <div class="card custom-card">
                        <div class="card-body d-flex justify-content-between align-items-center custom-card-body">
                            <div class="form-check custom-form-check">
                                <form action="{% url 'todo-overdue-task' cont.id %}" method="POST" id="form-{{ cont.id }}">
                                    {% csrf_token %}
                                    <input class="form-check-input custom-form-check-input" type="checkbox" name="completed" value="True" id="flexCheckDefault{{ cont.id }}" {% if cont.completed %}checked{% endif %} onchange="document.getElementById('form-{{ cont.id }}').submit();">
                                    <label class="form-check-label custom-form-check-label" for="flexCheckDefault{{ cont.id }}">
                                        {{ cont.title }}
                                    </label>
                                </form>
                            </div>
                            <span class="btn custom-btn"> <b>&#8618;</b> </span>
                        </div>
                    </div>
                </a>
            {% endfor %}
        </div>

{% endblock %}

{% block task_detail %}

<form method="post">
                   <div class="form-container">
                       <h2>Task:</h2>
                      {% csrf_token %}
                      <div class="form-group">
                        <label for="id_title">Title</label>
                        <div class="input-container">
                          <input type="text" name="title" id="id_title" class="form-control custom-title" value="{{ form.title.value|default_if_none:'' }}">
                        </div>
                      </div>
                      <div class="form-group">
                        <label for="id_description">Description</label>
                        <div class="input-container">
                          <textarea name="description" id="id_description" class="form-control custom-description">{{ form.description.value|default_if_none:'' }}</textarea>
                        </div>
                      </div>
                        <div class="form-group">
                          <label for="id_due_date">Due Date</label>
                          <div class="input-container">
                            <input type="date" name="date" id="id_due_date" class="form-control custom-due-date" value="{{ form.date.value|date:'Y-m-d'|default_if_none:'' }}">
                          </div>
                        </div>
                        <div class="form-group">
                            <label for="id_tags">Tags</label>
                            <div class="input-container">
                                {{ form.tag }}
                            </div>
                        </div>

                           {% if edit %}
                                <div class="button-group">
                                    <button type="submit" class="btn custom-submit custom-save-1">Save Changes</button>
                                    <a href="{% url 'delete-overdue-task' task.id %}" class="btn custom-submit custom-delete-1">Delete</a>
                                </div>
                           {% else %}
                                <button type="submit" class="btn custom-submit">Add Task</button>
                           {% endif %}
                   </div>
               </form>

{% endblock %}

</body>
</html>